# Generated by Django 5.0.6 on 2024-06-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='total_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='total_review',
            field=models.IntegerField(default=1),
        ),
    ]
