# Generated by Django 5.0.6 on 2024-06-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_smartphone_total_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='total_rating',
            new_name='totalrating',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='total_review',
            new_name='totalreview',
        ),
    ]
