# Generated by Django 5.0.6 on 2024-06-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_total_rating_smartphone_totalrating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='smartphone',
        ),
    ]
