# Generated by Django 5.0.6 on 2024-06-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_book_review_smartphone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
